name: srivik
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Icons & UI
  cupertino_icons: ^1.0.8

  # Backend & Database (Firebase / Supabase)
  # firebase_core: ^3.0.0
  # firebase_auth: ^5.0.0
  # cloud_firestore: ^5.0.0
  # supabase_flutter: ^2.5.0

  # Ads / Monetization
  # google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # প্রজেক্টে কোনো ছবি বা ফন্ট থাকলে নিচে এভাবে যুক্ত করতে পারেন
  # assets:
  #   - assets/images/
